config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :articles
  # resources :mypage
  root "articles#index"
  get "mypage" => "mypage#show"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true
  belongs_to :user

  has_many :article_tags, dependent: :destroy
  has_many :tags, through: :article_tags
end

app/models/article_tag.rb
class ArticleTag < ApplicationRecord
  belongs_to :article
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
  validates :name, presence: true

  has_many :article_tags, dependent: :destroy
  has_many :articles, through: :article_tags
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
  before_action :authenticate_user!
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, except: %i[ index show ]
  before_action :set_article, only: %i[ edit update destroy ]

  def index
    @articles = Article.all.page params[:page]
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = current_user.articles.new(article_params)
    if @article.save
      redirect_to @article, notice: "#{t('activerecord.models.article')}を作成しました。"
    else
      render :new
    end
  end

  def edit
  end

  def update
   if @article.update!(article_params)
    redirect_to @article, notice: "#{t('activerecord.models.article')}を編集しました。"
   else
    render :edit
   end
  end

  def destroy
    @article.destroy
    redirect_to articles_url, notice: "#{t('activerecord.models.article')}を削除しました。"
  end

 private
   #ストロングパラメーターの実装
  def article_params
    params.require(:article).permit(:title, :content)
  end

  def set_article
    @article = current_user.articles.find(params[:id])
  end
end

app/controllers/mypage_controller.rb
class MypageController < ApplicationController
  before_action :authenticate_user!
  before_action :set_article, only: %i[ edit update destroy ]

  def show
    articles = current_user.articles
    articles = articles.where("title LIKE ?", "%#{params[:title]}%") if params[:title].present?
    @articles = articles.page params[:page]
  end
end
 private
  #  #ストロングパラメーターの実装
  # def article_params
  #   params.require(:article).permit(:title, :content)
  # end

#   def set_article
#     @article = current_user.articles.find(params[:id])
#   end
# end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<%= form_with(model: article, local: true) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= article.errors.count%> 件の対応が必要です</h2>

      <ul>
        <% article.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

 <div class="mb-3">
   <%= form.collection_check_boxes :tag_ids, Tag.all, :id, :name %>
 </div>

 <div class="mb-3">
    <%= form.label :title, class: "form-label" %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :content, class: "form-label" %>
    <%= form.text_area :content, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit '保存', class: "btn btn-primary" %>
  </div>
<% end %>

app/views/articles/_search.html.erb
<%= form_with url: articles_url, method: :get, local: true do |form| %>
  <div class="row justify-content-center">
    <div class="col-6">
      <div class="mb-3">
        <%= form.label 'タイトル', class: "form-label" %>
        <%= form.text_field :title, value: params[:title], class: "form-control" %>
      </div>
      <div class="actions">
        <%= form.submit '検索', class: "btn btn-primary" %>
      </div>
    </div>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>記事編集</h1>

<%= render 'form', article: @article %>
<%= link_to '詳細', @article, class: "btn btn-success"  %>
<%= link_to '一覧', articles_path, class: "btn btn-secondary" %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>記事</h1>
  <%= paginate @articles %>
 <%= render partial: "search" %>
<table class="table">
  <thead>
    <tr>
      <th scope="col">タイトル</th>
      <th scope="col">内容</th>
    </tr>
  </thead>
  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td>
            <%= article.title %>
            <% article.tags.each do |tag| %>
              <span class="badge rounded-pill bg-primary"><%= tag.name%></span>
            <% end %>
         </td>
        <td><%= article.content %></td>
        <td>
          <%= link_to '詳細', article, class: "btn btn-success" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/articles/new.html.erb
<h1>記事作成</h1>

<%= render 'form', article: @article %>

<%= link_to '一覧', articles_path, class: "btn btn-secondary" %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<div class="card">
  <div class="card-header">
    <%= @article.title %>
      <% @article.tags.each do |tag| %>
        <span class="badge rounded-pill bg-primary"><%= tag.name%></span>
      <% end %>
  </div>
  <div class="card-body">
    <%= @article.content %>
  </div>
</div>
<% if current_user&.id == @article.user_id %>
<%= link_to '編集', edit_article_path(@article), class: "btn btn-warning" %>
<% end %>
<%= link_to '一覧', articles_path, class: "btn btn-secondary" %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-sm navbar-success bg-light">
  <div class="container-fluid">
    <%= link_to "トップ", root_path, class: "navbar-brand" %>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
          <% if user_signed_in? %>
          <li class="nav-item">
           <%= link_to "マイページ", mypage_path, class: "nav-link active"%>
          </li>
          <li class="nav-item">
           <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-link active"%>
          </li>
          <% else %>
          <li class="nav-item">
            <%= link_to "サインアップ", new_user_registration_path, class: "nav-link active" %>
          </li>
          <li class="nav-item">
            <%= link_to "ログイン", new_user_session_path, class: "nav-link active"%>
          </li>
          <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WonderfulPostApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <%= render partial: "layouts/navbar" %>
   <div class="container">
    <%= yield %>
   </div>
  </body>
</html>

app/views/mypage/_form.html.erb
<%= form_with(model: article, local: true) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= article.errors.count%> 件の対応が必要です</h2>

      <ul>
        <% article.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

 <div class="mb-3">
    <%= form.label :title, class: "form-label" %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :content, class: "form-label" %>
    <%= form.text_area :content, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit '保存', class: "btn btn-primary" %>
  </div>
<% end %>

app/views/mypage/_search.html.erb
<%= form_with url: mypage_url, method: :get, local: true do |form| %>
  <div class="row justify-content-center">
    <div class="col-6">
      <div class="mb-3">
        <%= form.label 'タイトル', class: "form-label" %>
        <%= form.text_field :title, value: params[:title], class: "form-control" %>
      </div>
      <div class="actions">
        <%= form.submit '検索', class: "btn btn-primary" %>
      </div>
    </div>
  </div>
<% end %>

app/views/mypage/index.html.erb
<p id="notice"><%= notice %></p>

<h1>マイページ</h1>
<%= link_to '記事作成', new_article_path, class: "btn btn-info" %>
<table class="table">
  <thead>
    <tr>
      <th scope="col">タイトル</th>
      <th scope="col">内容</th>
    </tr>
  </thead>
  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td>
           <%= article.title %>
           <% article.tags.each do |tag| %>
             <span class="badge rounded-pill bg-primary"><%= tag.name%></span>
           <% end %>
        </td>
        <td><%= article.content %></td>
        <td>
          <%= link_to '詳細', article, class: "btn btn-success" %>
          <%= link_to '編集', edit_article_path(article), class: "btn btn-warning" %>
          <%= link_to '削除', article, class: "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/mypage/show.html.erb
<p id="notice"><%= notice %></p>

<h1>マイページ</h1>
 <%= paginate @articles %>
 <%= render partial: "search" %>
<%= link_to '記事作成', new_article_path, class: "btn btn-info" %>
<table class="table">
  <thead>
    <tr>
      <th scope="col">タイトル</th>
      <th scope="col">内容</th>
    </tr>
  </thead>
  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.content %></td>
        <td>
          <%= link_to '詳細', article, class: "btn btn-success" %>
          <%= link_to '編集', edit_article_path(article), class: "btn btn-warning" %>
          <%= link_to '削除', article, class: "btn btn-danger", method: :delete, data: { confirm: '削除してよろしいですか？' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>